detectors:
  Attribute:
    exclude: []
  ControlParameter:
    exclude: []
  DataClump:
    exclude: []
  DuplicateMethodCall:
    exclude: []
  FeatureEnvy:
    exclude: []
  LongParameterList:
    exclude: []
  NilCheck:
    exclude: []
  InstanceVariableAssumption:
    exclude: []
  TooManyInstanceVariables:
    exclude: []
  TooManyMethods:
    exclude: []
  TooManyStatements:
    exclude: []
  UncommunicativeVariableName:
    accept:
      - e
  UtilityFunction:
    exclude: []
