detectors:
  Attribute:
    exclude:
      - Qni::View::DrawElement#layer_width
  ControlParameter:
    exclude: []
  DataClump:
    exclude: []
  DuplicateMethodCall:
    exclude: []
  FeatureEnvy:
    exclude:
      - Qni::KittyGraphicsEmitter#emit_payload
  LongParameterList:
    exclude:
      - Qni::View::DrawElement#render_line
  NilCheck:
    exclude: []
  InstanceVariableAssumption:
    exclude:
      - Qni::Circuit
  TooManyInstanceVariables:
    exclude:
      - Qni::View::DrawElement
      - Qni::View::BoxOnQuWire
      - Qni::View::DirectOnQuWire
  TooManyMethods:
    exclude:
      - Qni::CLI::BlochCommand
      - Qni::Circuit
  TooManyStatements:
    exclude:
      - Qni::View::DrawElement#initialize
      - Qni::View::BoxOnQuWire#initialize
  UncommunicativeVariableName:
    accept:
      - e
  UtilityFunction:
    exclude:
      - Qni::BlochRenderer#resolved_result
